require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  CacheRootDirectory: tmp/rubocop_cache
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.2.2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/Documentation:
  Enabled: false
